name:                       golang-pipeline
on:                         push
jobs:
  test:
    runs-on:                ubuntu-latest
    if:                     github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses:               actions/checkout@v2
      - name:               Set WORK_DIR
        run:                echo WORK_DIR=$(echo $GITHUB_REPOSITORY | grep -Eo 'atlas-(.*)' | cut -f2- -d- | perl -ne 'print "./atlas.com/$_"') >> $GITHUB_ENV
      - name:               Run Unit Tests
        working-directory:  ${{ env.WORK_DIR }}
        run:                go test

  deploy:
    runs-on:                ubuntu-latest
    needs:                  test
    if:                     ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name:               Define Tag
        run:                echo IMAGE_TAG=$(echo $GITHUB_REPOSITORY:latest) >> $GITHUB_ENV
      - name:               Login to DockerHub
        uses:               docker/login-action@v1
        with:
          username:         ${{ secrets.DOCKER_USERNAME }}
          password:         ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name:               Build and push
        uses:               docker/build-push-action@v2
        with:
          push:             true
          tags:             ${{ env.IMAGE_TAG }}
